apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: exchange-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.39
          ports:
            - containerPort: 16686
            - containerPort: 6831
            - containerPort: 14268
          env:
            - name: COLLECTOR_ZIPKIN_HOST_PORT
              value: ':9411'
